export const SYSTEM_ACTORS = {
  PROCUREMENT: 'SYSTEM_PROCUREMENT',
  INVENTORY: 'SYSTEM_INVENTORY',
  ASSET: 'SYSTEM_ASSET',
  NOTIFICATION: 'SYSTEM_NOTIFICATION',
  ANALYTICS: 'SYSTEM_ANALYTICS',
} as const;

export type SystemActor = typeof SYSTEM_ACTORS[keyof typeof SYSTEM_ACTORS];
