export const PERMISSIONS = {
  CREATE_ASSET: 'CREATE_ASSET',
  UPDATE_ASSET: 'UPDATE_ASSET',
  DELETE_ASSET: 'DELETE_ASSET',
  APPROVE_TRANSFER: 'APPROVE_TRANSFER',
  APPROVE_MAINTENANCE: 'APPROVE_MAINTENANCE',
  VIEW_REPORTS: 'VIEW_REPORTS',
} as const;
