import { ROLES, Role } from './roles';

export const PERMISSIONS = {
  // Users
  CREATE_USER: 'CREATE_USER',
  READ_USER: 'READ_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  // Departments
  CREATE_DEPARTMENT: 'CREATE_DEPARTMENT',
  READ_DEPARTMENT: 'READ_DEPARTMENT',
  UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
  DELETE_DEPARTMENT: 'DELETE_DEPARTMENT',

  // Assets
  CREATE_ASSET: 'CREATE_ASSET',
  READ_ASSET: 'READ_ASSET',
  UPDATE_ASSET: 'UPDATE_ASSET',
  DELETE_ASSET: 'DELETE_ASSET',

  // System & Workflow
  APPROVE_TRANSFER: 'APPROVE_TRANSFER',
  APPROVE_MAINTENANCE: 'APPROVE_MAINTENANCE',
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  MANAGE_SYSTEM: 'MANAGE_SYSTEM',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS), // Admin has all permissions
  [ROLES.ASSET_MANAGER]: [
    PERMISSIONS.READ_USER,
    PERMISSIONS.READ_DEPARTMENT,
    PERMISSIONS.CREATE_ASSET,
    PERMISSIONS.READ_ASSET,
    PERMISSIONS.UPDATE_ASSET,
    PERMISSIONS.DELETE_ASSET,
    PERMISSIONS.APPROVE_MAINTENANCE,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.DEPARTMENT_HEAD]: [
    PERMISSIONS.READ_USER,
    PERMISSIONS.READ_DEPARTMENT,
    PERMISSIONS.READ_ASSET,
    PERMISSIONS.UPDATE_ASSET,
    PERMISSIONS.APPROVE_TRANSFER,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.EMPLOYEE]: [PERMISSIONS.READ_USER, PERMISSIONS.READ_DEPARTMENT, PERMISSIONS.READ_ASSET],
};
